In [1]:
# import libraries
import pandas as pd

In [2]:
# load in flat file as df
df = pd.read_csv("../Data/bookstore_flat.csv")

In [3]:
# inspect the df
df.head()

,transaction_id,transaction_date,member_id,member_first_name,member_last_name,member_email,member_tier,member_join_date,member_city,member_state,...,author_first,author_last,publisher_name,publisher_city,publisher_country,publication_year,list_price,quantity,discount_percent,sale_total
0,1,2019-10-05,260,Casey,Jackson,casey.jackson260@email.com,Platinum,2018-12-09,New York,WA,...,Celeste,Ng,Macmillan Publishers,New York,USA,2006,19.23,3,20,46.14
1,2,2019-12-22,292,Marcus,Walker,marcus.walker292@email.com,Platinum,2020-06-11,Portland,CO,...,Erik,Larson,Hachette Book Group,New York,USA,2008,28.46,1,0,28.46
2,3,2019-03-09,30,Bailey,Anderson,bailey.anderson30@email.com,Bronze,2018-05-26,Austin,TX,...,Isabel,Allende,Scholastic,New York,USA,2020,34.94,1,5,33.19
3,4,2020-02-12,185,Ethan,King,ethan.king185@email.com,Bronze,2018-01-05,Portland,CA,...,Jhumpa,Lahiri,Penguin Random House,New York,USA,2012,31.17,2,0,62.34
4,5,2021-03-23,238,Kenji,Scott,kenji.scott238@email.com,Gold,2022-10-28,Coral Gables,OR,...,N.K.,Jemisin,Hachette Book Group,New York,USA,2007,19.10,1,15,16.23

In [6]:
df.columns

Index(['transaction_id', 'transaction_date', 'member_id', 'member_first_name',
       'member_last_name', 'member_email', 'member_tier', 'member_join_date',
       'member_city', 'member_state', 'store_name', 'store_city',
       'store_state', 'store_region', 'book_id', 'isbn', 'title', 'genre',
       'format', 'author_first', 'author_last', 'publisher_name',
       'publisher_city', 'publisher_country', 'publication_year', 'list_price',
       'quantity', 'discount_percent', 'sale_total'],
      dtype='str')

In [8]:
df['publisher_country'].value_counts()

publisher_country
USA    4639
UK      561
Name: count, dtype: int64

Use this markdown cell to write notes needed to design the new relational db schema

- transactions = ['transaction_id','store_id','transaction_date','member_id','book_id','quantity','discount_percent']

- members = ['member_id','member_first_name','member_last_name','member_email','member_tier','member_join_date','member_city','member_state'] 

- stores = ['store_id','store_name','store_city','store_state','store_region'] ***need store_id 

- authors = ['author_id','author_first','author_last'] ** need author_id

- publishers = ['publisher_id','publisher_name','publisher_city','publisher_country'] ** need publisher_id 

- books = ['book_id','isbn','title','genre','format','author_id','publication_year','publication_id','list_price'] ** author_id

In [14]:
# filter the df into tables matching the schema in the markdown cell above

members_df = df[['member_id','member_first_name','member_last_name','member_email','member_tier','member_join_date','member_city','member_state']].drop_duplicates()
members_df.head()

,member_id,member_first_name,member_last_name,member_email,member_tier,member_join_date,member_city,member_state
0,260,Casey,Jackson,casey.jackson260@email.com,Platinum,2018-12-09,New York,WA
1,292,Marcus,Walker,marcus.walker292@email.com,Platinum,2020-06-11,Portland,CO
2,30,Bailey,Anderson,bailey.anderson30@email.com,Bronze,2018-05-26,Austin,TX
3,185,Ethan,King,ethan.king185@email.com,Bronze,2018-01-05,Portland,CA
4,238,Kenji,Scott,kenji.scott238@email.com,Gold,2022-10-28,Coral Gables,OR

In [15]:
members_df.member_id.value_counts()

member_id
260    1
292    1
30     1
185    1
238    1
      ..
164    1
143    1
39     1
35     1
101    1
Name: count, Length: 300, dtype: int64

In [18]:
stores_df = df[['store_name','store_city','store_state','store_region']].drop_duplicates().reset_index(drop=True)
stores_df

              store_name     store_city store_state store_region
0         Prairie Lights      Iowa City          IA      Midwest
1         Powell's Books       Portland          OR      Pacific
2             BookPeople         Austin          TX        South
3        Left Bank Books      St. Louis          MO      Midwest
4   Malaprop's Bookstore      Asheville          NC        South
5     Elliot Bay Book Co        Seattle          WA      Pacific
6     Harvard Book Store      Cambridge          MA    Northeast
7          Books & Books   Coral Gables          FL        South
8          The Booksmith  San Francisco          CA      Pacific
9         Tattered Cover         Denver          CO     Mountain
10        Kepler's Books     Menlo Park          CA      Pacific
11            The Strand       New York          NY    Northeast

In [20]:
stores_df.insert(0, 'store_id', range(1,len(stores_df)+1))
stores_df

    store_id            store_name     store_city store_state store_region
0          1        Prairie Lights      Iowa City          IA      Midwest
1          2        Powell's Books       Portland          OR      Pacific
2          3            BookPeople         Austin          TX        South
3          4       Left Bank Books      St. Louis          MO      Midwest
4          5  Malaprop's Bookstore      Asheville          NC        South
5          6    Elliot Bay Book Co        Seattle          WA      Pacific
6          7    Harvard Book Store      Cambridge          MA    Northeast
7          8         Books & Books   Coral Gables          FL        South
8          9         The Booksmith  San Francisco          CA      Pacific
9         10        Tattered Cover         Denver          CO     Mountain
10        11        Kepler's Books     Menlo Park          CA      Pacific
11        12            The Strand       New York          NY    Northeast

In [22]:
authors_df = df[['author_first','author_last']].drop_duplicates().reset_index(drop=True)
authors_df.insert(0, 'author_id', range(1,len(authors_df)+1))
authors_df.head()

   author_id author_first author_last
0          1      Celeste          Ng
1          2         Erik      Larson
2          3       Isabel     Allende
3          4       Jhumpa      Lahiri
4          5         N.K.     Jemisin

In [23]:
publishers_df = df[['publisher_name','publisher_city','publisher_country']].drop_duplicates().reset_index(drop=True)
publishers_df.insert(0, 'publisher_id', range(1,len(publishers_df)+1))
publishers_df.head()

   publisher_id        publisher_name publisher_city publisher_country
0             1  Macmillan Publishers       New York               USA
1             2   Hachette Book Group       New York               USA
2             3            Scholastic       New York               USA
3             4  Penguin Random House       New York               USA
4             5            Bloomsbury         London                UK

In [34]:
books_df = df[['book_id','isbn','title','genre','format','author_first','author_last','publication_year','publisher_name','list_price']].drop_duplicates().reset_index(drop=True)
books_df.head()

,book_id,isbn,title,genre,format,author_first,author_last,publication_year,publisher_name,list_price
0,182,978-529-93748-89-7,The Long Road Vol. 6,Biography,Paperback,Celeste,Ng,2006,Macmillan Publishers,19.23
1,226,978-119-67807-50-6,The Lost Century Vol. 2,History,Hardcover,Erik,Larson,2008,Hachette Book Group,28.46
2,215,978-578-75373-49-7,Empire Rising Vol. 7,History,Paperback,Isabel,Allende,2020,Scholastic,34.94
3,236,978-856-14888-32-6,Turning Points Vol. 4,History,Hardcover,Jhumpa,Lahiri,2012,Penguin Random House,31.17
4,211,978-161-30719-66-6,Empire Rising Vol. 3,History,Audiobook,N.K.,Jemisin,2007,Hachette Book Group,19.10

In [35]:
books_df = books_df.merge(authors_df[['author_id','author_first','author_last']], left_on=['author_first','author_last'], right_on = ['author_first','author_last'], how='left')
books_df.head(3)

,book_id,isbn,title,genre,format,author_first,author_last,publication_year,publisher_name,list_price,author_id
0,182,978-529-93748-89-7,The Long Road Vol. 6,Biography,Paperback,Celeste,Ng,2006,Macmillan Publishers,19.23,1
1,226,978-119-67807-50-6,The Lost Century Vol. 2,History,Hardcover,Erik,Larson,2008,Hachette Book Group,28.46,2
2,215,978-578-75373-49-7,Empire Rising Vol. 7,History,Paperback,Isabel,Allende,2020,Scholastic,34.94,3

In [36]:
books_df = books_df.drop(columns=['author_first','author_last'])
books_df.head()

,book_id,isbn,title,genre,format,publication_year,publisher_name,list_price,author_id
0,182,978-529-93748-89-7,The Long Road Vol. 6,Biography,Paperback,2006,Macmillan Publishers,19.23,1
1,226,978-119-67807-50-6,The Lost Century Vol. 2,History,Hardcover,2008,Hachette Book Group,28.46,2
2,215,978-578-75373-49-7,Empire Rising Vol. 7,History,Paperback,2020,Scholastic,34.94,3
3,236,978-856-14888-32-6,Turning Points Vol. 4,History,Hardcover,2012,Penguin Random House,31.17,4
4,211,978-161-30719-66-6,Empire Rising Vol. 3,History,Audiobook,2007,Hachette Book Group,19.10,5

In [38]:
books_df = books_df.merge(publishers_df[['publisher_name', 'publisher_id']], on='publisher_name', how='left')
books_df.head()

,book_id,isbn,title,genre,format,publication_year,publisher_name,list_price,author_id,publisher_id
0,182,978-529-93748-89-7,The Long Road Vol. 6,Biography,Paperback,2006,Macmillan Publishers,19.23,1,1
1,226,978-119-67807-50-6,The Lost Century Vol. 2,History,Hardcover,2008,Hachette Book Group,28.46,2,2
2,215,978-578-75373-49-7,Empire Rising Vol. 7,History,Paperback,2020,Scholastic,34.94,3,3
3,236,978-856-14888-32-6,Turning Points Vol. 4,History,Hardcover,2012,Penguin Random House,31.17,4,4
4,211,978-161-30719-66-6,Empire Rising Vol. 3,History,Audiobook,2007,Hachette Book Group,19.10,5,2

In [39]:
books_df = books_df.drop(columns='publisher_name')
books_df.head()

,book_id,isbn,title,genre,format,publication_year,list_price,author_id,publisher_id
0,182,978-529-93748-89-7,The Long Road Vol. 6,Biography,Paperback,2006,19.23,1,1
1,226,978-119-67807-50-6,The Lost Century Vol. 2,History,Hardcover,2008,28.46,2,2
2,215,978-578-75373-49-7,Empire Rising Vol. 7,History,Paperback,2020,34.94,3,3
3,236,978-856-14888-32-6,Turning Points Vol. 4,History,Hardcover,2012,31.17,4,4
4,211,978-161-30719-66-6,Empire Rising Vol. 3,History,Audiobook,2007,19.10,5,2

In [40]:
transaction_df = df[['transaction_id','store_name','transaction_date','member_id','book_id','quantity','discount_percent']].drop_duplicates().reset_index(drop=True)
transaction_df.head()

,transaction_id,store_name,transaction_date,member_id,book_id,quantity,discount_percent
0,1,Prairie Lights,2019-10-05,260,182,3,20
1,2,Powell's Books,2019-12-22,292,226,1,0
2,3,BookPeople,2019-03-09,30,215,1,5
3,4,Left Bank Books,2020-02-12,185,236,2,0
4,5,Malaprop's Bookstore,2021-03-23,238,211,1,15

In [41]:
transaction_df = transaction_df.merge(stores_df[['store_id', 'store_name']], on='store_name', how='left')
transaction_df = transaction_df.drop(columns='store_name')
transaction_df.head()

,transaction_id,transaction_date,member_id,book_id,quantity,discount_percent,store_id
0,1,2019-10-05,260,182,3,20,1
1,2,2019-12-22,292,226,1,0,2
2,3,2019-03-09,30,215,1,5,3
3,4,2020-02-12,185,236,2,0,4
4,5,2021-03-23,238,211,1,15,5

In [ ]:
# save each of the new dfs as their own csv files

In [ ]:
# create the database and load all new dfs as tables. make sure to save the db in the data folder.